# Pre-commit configuration for memory-gate project
# This configuration includes ruff, black, mypy, and isort hooks
# aligned with the project's pyproject.toml settings

repos:
# Ruff - Fast Python linter and formatter (replaces flake8, isort, and more)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.1
    hooks:
      # Ruff linter with safe auto-fixes enabled
      - id: ruff
        name: ruff-lint
        args: [--fix, --exit-non-zero-on-fix]
        types_or: [python, pyi, jupyter]
        require_serial: false

      # Ruff formatter (optional, since we're using Black as well)
      - id: ruff-format
        name: ruff-format
        types_or: [python, pyi, jupyter]
        require_serial: false

# Black - Python code formatter
  # Using ruff format instead of black for consistency

  # isort - Import sorting (disabled since ruff handles it)
  # - repo: https://github.com/pycqa/isort
  #   rev: 5.13.2
  #   hooks:
  #     - id: isort
  #       name: isort-check
  #       args: [--check-only, --diff]
  #       types: [python]

  # MyPy - Static type checker with strict mode
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.1
    hooks:
      - id: mypy
        name: mypy-strict
        # Use config from pyproject.toml
        args: [--config-file=pyproject.toml]
        language_version: python3.13
        types: [python]
        # Include additional dependencies that mypy needs for checking
        additional_dependencies: [
          "pydantic>=2.0.0",
          "numpy>=1.24.0",
          "prometheus-client>=0.19.0",
          "pytest>=8.0.0",
          "types-redis",
        ]
        # Focus mypy on source code only, not tests (to reduce noise)
        files: ^src/

  # Additional quality checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # Check for merge conflicts
      - id: check-merge-conflict
      
      # Check YAML files
      - id: check-yaml
        args: [--unsafe]  # Allow custom YAML tags
        exclude: ^helm/.*\.yaml$  # Exclude Helm templates (contain Go template syntax)
      
      # Check for large files (>500KB)
      - id: check-added-large-files
        args: [--maxkb=500]
      
      # Ensure files end with newline
      - id: end-of-file-fixer
        types: [python]
      
      # Remove trailing whitespace
      - id: trailing-whitespace
        types: [python]
      
      # Check for private key files
      - id: detect-private-key
      
      # Check for AWS credentials
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]

# Security checks
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.5
    hooks:
      - id: bandit
        name: bandit-security-check
        args: [-c, pyproject.toml]
        types: [python]
        # Skip test files as they often use assert and other testing patterns
        exclude: ^tests/

  # Safety check for dependency vulnerabilities
  - repo: local
    hooks:
      - id: safety
        name: safety
        entry: safety scan --full-report
        language: system
        files: (requirements.*\.txt|pyproject\.toml)$
        pass_filenames: false

# Global pre-commit configuration
default_language_version:
  python: python3.13

# Fail fast - stop running hooks after first failure
fail_fast: false

# Repository-wide settings
minimum_pre_commit_version: "3.0.0"
