name: Continuous Integration

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  code-quality:
    name: Code Quality
    uses: ./.github/workflows/lint.yml
    with:
      python-version: '3.13'
      target-dirs: 'src tests'
      
  security:
    name: Security Analysis
    uses: ./.github/workflows/security.yml
    with:
      python-version: '3.13'
      
  unit-tests:
    name: Unit Tests
    uses: ./.github/workflows/test.yml
    needs: [code-quality]
    with:
      python-version: '3.13'
      test-type: 'unit'
      coverage-threshold: '85'
      
  integration-tests:
    name: Integration Tests
    uses: ./.github/workflows/test.yml
    needs: [unit-tests]
    with:
      python-version: '3.13'
      test-type: 'integration'
      coverage-threshold: '75'
      
  regression-tests:
    name: Regression Tests
    uses: ./.github/workflows/test.yml
    needs: [integration-tests]
    with:
      python-version: '3.13'
      test-type: 'regression'
      coverage-threshold: '85'
      
  ci-complete:
    name: CI Complete
    runs-on: ubuntu-latest
    needs: [code-quality, security, unit-tests, integration-tests, regression-tests]
    if: always()
    steps:
    - name: Check all jobs status
      run: |
        echo "Code Quality: ${{ needs.code-quality.result }}"
        echo "Security: ${{ needs.security.result }}"
        echo "Unit Tests: ${{ needs.unit-tests.result }}"
        echo "Integration Tests: ${{ needs.integration-tests.result }}"
        echo "Regression Tests: ${{ needs.regression-tests.result }}"
        
        if [[ "${{ needs.code-quality.result }}" != "success" || 
              "${{ needs.security.result }}" != "success" || 
              "${{ needs.unit-tests.result }}" != "success" || 
              "${{ needs.integration-tests.result }}" != "success" || 
              "${{ needs.regression-tests.result }}" != "success" ]]; then
          echo "One or more CI steps failed"
          exit 1
        fi
        echo "All CI steps completed successfully"
