name: Code Quality

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to use'
        required: false
        default: '3.13'
        type: string
      target-dirs:
        description: 'Directories to lint (space-separated)'
        required: false
        default: 'src tests'
        type: string
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        
    - name: Install dependencies
      run: |
        uv sync --group dev-essential
        
    - name: Run Ruff linting
      run: |
        uv run ruff check ${{ inputs.target-dirs }}
        
    - name: Run Ruff formatting check
      run: |
        uv run ruff format --check ${{ inputs.target-dirs }}
        
    - name: Run type checking with MyPy
      run: |
        uv run mypy src
